[package]
name = "texla-client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tungstenite = "0.24.0"
